# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Python\B3603CountolQt\ui\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 185)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/flash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbControl = QtWidgets.QGroupBox(self.centralwidget)
        self.gbControl.setObjectName("gbControl")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbControl)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leVoltage = QtWidgets.QLineEdit(self.gbControl)
        self.leVoltage.setText("0")
        self.leVoltage.setMaxLength(5)
        self.leVoltage.setFrame(True)
        self.leVoltage.setObjectName("leVoltage")
        self.horizontalLayout_4.addWidget(self.leVoltage)
        self.label = QtWidgets.QLabel(self.gbControl)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.gbControl)
        self.leMinus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.leMinus.setFont(font)
        self.leMinus.setObjectName("leMinus")
        self.horizontalLayout_2.addWidget(self.leMinus)
        self.gbOptions = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbOptions.sizePolicy().hasHeightForWidth())
        self.gbOptions.setSizePolicy(sizePolicy)
        self.gbOptions.setObjectName("gbOptions")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbOptions)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leVoltageOfst = QtWidgets.QLineEdit(self.gbOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leVoltageOfst.sizePolicy().hasHeightForWidth())
        self.leVoltageOfst.setSizePolicy(sizePolicy)
        self.leVoltageOfst.setText("0")
        self.leVoltageOfst.setMaxLength(5)
        self.leVoltageOfst.setFrame(True)
        self.leVoltageOfst.setObjectName("leVoltageOfst")
        self.horizontalLayout_3.addWidget(self.leVoltageOfst)
        self.lbVoltageCap = QtWidgets.QLabel(self.gbOptions)
        self.lbVoltageCap.setObjectName("lbVoltageCap")
        self.horizontalLayout_3.addWidget(self.lbVoltageCap)
        self.horizontalLayout_2.addWidget(self.gbOptions)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbSet = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbSet.setObjectName("pbSet")
        self.horizontalLayout.addWidget(self.pbSet)
        self.pbOff = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pbOff.setObjectName("pbOff")
        self.horizontalLayout.addWidget(self.pbOff)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "B3603"))
        self.gbControl.setTitle(_translate("MainWindow", "Contol"))
        self.leVoltage.setInputMask(_translate("MainWindow", "99999"))
        self.label.setText(_translate("MainWindow", "mV"))
        self.leMinus.setText(_translate("MainWindow", "-"))
        self.gbOptions.setTitle(_translate("MainWindow", "Offsets"))
        self.leVoltageOfst.setInputMask(_translate("MainWindow", "99999"))
        self.lbVoltageCap.setText(_translate("MainWindow", "mV"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.pbSet.setText(_translate("MainWindow", "Set"))
        self.pbOff.setText(_translate("MainWindow", "OFF"))


import res_rc
